apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeploy
  namespace: prod
  labels:
    name: deployment
  annotations:
    kubernetes.io/change-cause: repo:${DOCKER_TAG}
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
       name: deploy-pods
       labels:
         env: prod
    spec:
      containers:
        - name: container1
          image: anirudh1101/kubernetes-test:repo:${DOCKER_TAG}
