apiVersion: v1
kind: Service
metadata:
  name: prod-service
  labels:
    servicelabel: service-prod
  namespace: prod
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 8080
      targetPort: 80
  selector:
    env: prod
